// Game-state entry point (task 1.1). Components import from here.
export {
  useGameStore,
  defaultSession,
  defaultSettings,
  defaultScore,
  defaultInventory,
  defaultDope,
  defaultChrono,
  MIL_CLICK_RAD,
  MOA_CLICK_RAD,
  COARSE_CLICKS,
  ZOOM_MIN,
  ZOOM_MAX,
  DEFAULT_MAGNIFICATION,
  DEFAULT_SHOT_BUDGET,
  DEFAULT_WIND_PRESET,
} from './store';
export type {
  GameStore,
  SessionState,
  SettingsState,
  ScopeState,
  WindState,
  WindRealism,
  MarkerStyle,
  UnitsPrimary,
  CommittedTarget,
  ScoreState,
  InventoryState,
  DopeState,
  ChronoState,
} from './store';
export {
  settingsToSave,
  saveToSettings,
  storeToSave,
  saveToInventory,
  saveToDope,
  saveToChrono,
  loadSettingsInto,
  persistSettingsOnChange,
} from './persist-settings';
